### ISSUE TITLE
Bunlar Hata Değil Reis Bir Bakarmısın 

### ISSUE THREAD

**Issue by vural1** [abdulkadiraktas/FxServerController#12]
8/24/2020-00:59:31 / [93mCouldn't find resource turkubarr.[0m

08/24/2020-00:59:38 / [31m[ERROR] connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [esx_inventoryhud_trunk] An error happens on MySQL for query "SELECT * FROM trunk_inventory": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [esx_inventoryhud_trunk] An error happens on MySQL for query "DELETE FROM `trunk_inventory` WHERE `owned` = 0": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [esx_society] An error happens on MySQL for query "SELECT * FROM jobs": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [esx_vehicleshopg] An error happens on MySQL for query "SELECT * FROM vehicle_categories": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [esx_addoninventory] An error happens on MySQL for query "SELECT * FROM items": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [atsiz_Nos] An error happens on MySQL for query "SELECT * FROM nitro_vehicles": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM items": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM jobs": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [31m[ERROR] [MySQL] [esx_helikopter_galerisi] An error happens on MySQL for query "SELECT * FROM heli_categories": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:38 / [91mSCRIPT ERROR: @es_extended/server/common.lua:23: bad argument #1 to 'for iterator' (table expected, got nil)[0m

08/24/2020-00:59:38 / [91mSCRIPT ERROR: @esx_inventoryhud_trunk/server/trunk.lua:21: attempt to get length of a nil value (local 'result')[0m

08/24/2020-00:59:38 / [91mSCRIPT ERROR: @esx_society/server/main.lua:31: attempt to get length of a nil value (local 'result')[0m

08/24/2020-00:59:38 / [91mSCRIPT ERROR: @esx_addoninventory/server/main.lua:10: attempt to get length of a nil value (local 'items')[0m

08/24/2020-00:59:38 / [91mSCRIPT ERROR: @atsiz_Nos/server/main.lua:9: attempt to get length of a nil value (local 'vehicles')[0m

08/24/2020-00:59:38 / [91mSCRIPT ERROR: @es_extended/server/common.lua:35: attempt to get length of a nil value (local 'result')[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [esx_vehicleshop] An error happens on MySQL for query "SELECT * FROM vehicle_categories": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [esx_addonaccount] An error happens on MySQL for query "SELECT * FROM addon_account": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [esx_boat] An error happens on MySQL for query "UPDATE owned_vehicles SET `stored` = true WHERE `stored` = false AND type = 'boat'": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [esx_datastore] An error happens on MySQL for query "SELECT * FROM datastore": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [esx_truckshop] An error happens on MySQL for query "SELECT * FROM truck_categories": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [esx_vehicleshopr] An error happens on MySQL for query "SELECT * FROM vehicle_categories": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [esx_whitelist] An error happens on MySQL for query "SELECT * FROM whitelist": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [gcphone] An error happens on MySQL for query "DELETE FROM phone_messages WHERE transmitter = 'police'": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [gcphone] An error happens on MySQL for query "DELETE FROM phone_messages WHERE transmitter = 'ambulance'": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [31m[ERROR] [MySQL] [gcphone] An error happens on MySQL for query "DELETE FROM phone_messages WHERE transmitter = 'news'": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:40 / [91mSCRIPT ERROR: @esx_whitelist/server/main.lua:7: attempt to get length of a nil value (local 'identifiers')[0m

08/24/2020-00:59:40 / [91mSCRIPT ERROR: @esx_addonaccount/server/main.lua:9: attempt to get length of a nil value (local 'result')[0m

08/24/2020-00:59:40 / [91mSCRIPT ERROR: @esx_datastore/server/main.lua:9: attempt to get length of a nil value (local 'result')[0m

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [esx_joblisting] An error happens on MySQL for query "SELECT name, label FROM jobs WHERE whitelisted = false": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [ygx_fishing] An error happens on MySQL for query "        INSERT

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [ygx_fishing] An error happens on MySQL for query "        INSERT

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [ygx_fishing] An error happens on MySQL for query "        INSERT

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [esx_helikopter_galerisi] An error happens on MySQL for query "SELECT * FROM heli": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [esx_vehicleshopg] An error happens on MySQL for query "SELECT * FROM vehicles": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:42 / [91mSCRIPT ERROR: @esx_joblisting/server/main.lua:10: attempt to get length of a nil value (local 'result')[0m

08/24/2020-00:59:42 / [91mSCRIPT ERROR: @esx_helikopter_galerisi/server/main.lua:28: attempt to get length of a nil value (local 'vehicles')[0m

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [esx_vehicleshop] An error happens on MySQL for query "SELECT * FROM vehicles": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [esx_truckshop] An error happens on MySQL for query "SELECT * FROM trucks": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:42 / [31m[ERROR] [MySQL] [esx_vehicleshopr] An error happens on MySQL for query "SELECT * FROM vehicles": connect ECONNREFUSED 127.0.0.1:3306[0m

08/24/2020-00:59:42 / [91mSCRIPT ERROR: @esx_vehicleshopg/server/main.lua:20: attempt to get length of a nil value (local 'vehicles')[0m

08/24/2020-00:59:42 / [91mSCRIPT ERROR: @esx_vehicleshop/server/main.lua:30: attempt to get length of a nil value (local 'vehicles')[0m

08/24/2020-00:59:42 / [91mSCRIPT ERROR: @esx_truckshop/server/main.lua:28: attempt to get length of a nil value (local 'vehicles')[0m

08/24/2020-00:59:42 / [91mSCRIPT ERROR: @esx_vehicleshopr/server/main.lua:20: attempt 

Bunlar Hata Değil Birçok Errorlar Yakında Local Vehicles araçla ilgili veri çekemediği için hata veren olaylar değilmi

**Comment by vural1** [comment]
Şöyle Bir Olay Var örnek truckshop 28.ci satır vehicleshop 30.satır girdiğim zaman araçla ilgili bir kod yazmışlar sizin programda araçla ilgili oyundan bir veri çekemediği için hata veriyor yani bunlar hata değilde yakınında araç olmadı için hata olarak gözüküyor yanlışmıyım

**Comment by abdulkadiraktas** [comment]
SCRIPT ERROR yazıyorsa o kod hatalıdır. Hatayı düzeltmen lazım.
