### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by schwim0341** [abdulkadiraktas/FxServerController#7]
After decompressing, running the exe results in a file select window.  What am I selecting?  run.cmd?  server-data?  Server.cfg?

The forum link in the readme results in a 404 and there's not a single mention in the readme concerning setup.  Could you let me know how to get the application to run for the first time?

Thanks!

**Comment by abdulkadiraktas** [comment]
https://youtu.be/kc34EwKI7sg

Please check video
