### ISSUE TITLE
No such command kickplayerforfxcontroller

### ISSUE THREAD

**Issue by Jhudri** [abdulkadiraktas/FxServerController#9]
I get this error when auto restarting and players don't get kicked, you also cant manually kick anybody.

note: im not using the auto announce feature, could that be the issue?

**Comment by abdulkadiraktas** [comment]
Please use this script for kick or announce system.
Requirement :
Updated : 10.07.2019 // please read readme for AnnonForFxController https://github.com/abdulkadiraktas/AnnonForFxController
